# Generated by Django 3.2.16 on 2024-04-19 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_title', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WatchedFilms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('kp_mark', models.FloatField(blank=True)),
                ('country', models.CharField(max_length=128)),
                ('genres', models.ManyToManyField(to='watched_films.Genre')),
                ('original_title', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watched_films.originaltitle')),
                ('product_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watched_films.producttype')),
            ],
        ),
    ]
