# Generated by Django 3.2.16 on 2024-04-23 13:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watched_films', '0002_auto_20240423_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('add_time',)},
        ),
        migrations.AlterModelOptions(
            name='originaltitle',
            options={'ordering': ('add_time',)},
        ),
        migrations.AlterModelOptions(
            name='watchedfilms',
            options={'ordering': ('add_time',)},
        ),
        migrations.AddField(
            model_name='watchedfilms',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2044)]),
        ),
    ]
