# Generated by Django 3.2.16 on 2024-04-24 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watched_films', '0003_auto_20240423_1653'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='country',
            field=models.CharField(max_length=128, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='genres',
            field=models.ManyToManyField(to='watched_films.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='kp_mark',
            field=models.FloatField(blank=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='original_title',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='watched_films.originaltitle', verbose_name='Оригинальное название'),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='watchedfilms',
            name='year',
            field=models.PositiveSmallIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2044)], verbose_name='Год'),
        ),
    ]
